CDPD-6167 : Add a config to switch execution mode to spark-acid
Change-Id: If7b379f28629400833f0e5d403e7a24281fa3576

diff --git a/build/scalastyle b/build/scalastyle
--- a/build/scalastyle
+++ b/build/scalastyle
@@ -1,5 +1,5 @@
-#
-# Copyright 2019 Qubole, Inc.  All rights reserved.
+#!/usr/bin/env bash
+
 #
 # Licensed to the Apache Software Foundation (ASF) under one or more
 # contributor license agreements.  See the NOTICE file distributed with
@@ -17,4 +17,16 @@
 # limitations under the License.
 #
 
-sbt.version=0.13.16
+# NOTE: echo "q" is needed because SBT prompts the user for input on encountering a build file
+# with failure (either resolution or compilation); the "q" makes SBT quit.
+ERRORS=$(echo -e "q\n" \
+    | build/sbt scalastyle test:scalastyle \
+    | awk '{if($1~/error/)print}' \
+)
+
+if test ! -z "$ERRORS"; then
+    echo -e "Scalastyle checks failed at following occurrences:\n$ERRORS"
+    exit 1
+else
+    echo -e "Scalastyle checks passed."
+fi
